A,B,C = list(map(float,input().split()))
tri=float(0.5*A*C)
crcl=float(3.14159*C*C)
trap=float((A+B)/2.0*C)
sqr=float(B*B)
rec=float(A*B)
print("TRIANGULO: %.3f"%tri)
print("CIRCULO: %.3f"%crcl)
print("TRAPEZIO: %.3f"%trap)
print("QUADRADO: %.3f"%sqr)
print("RETANGULO: %.3f"%rec)
